
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - MINIO_ACCESS_KEY=6bv5JNcebDunuN3W
      - MINIO_SECRET_KEY=Th8NPz6d6s9gM8HW6zDlMbTb98NnFH57
      - MINIO_BUCKET_NAME=data
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=1234
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=1234
  minio:
    image: minio/minio:RELEASE.2023-03-24T21-41-23Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ACCESS_KEY: test
      MINIO_SECRET_KEY: test12334567
    command: server /data --console-address ":9001"



volumes:
  dev-db-data:
  minio-data:
    driver: local